const books = [
  { id: 1, title: "The Effective Executive", price: 15 },
  { id: 2, title: "The Good Girl's Guide to Being a Dick", price: 12 },
  { id: 3, title: "TED Talks", price: 13 },
  { id: 4, title: "All In on AI", price: 15 },
  { id: 5, title: "The Power of Your Subconscious Mind", price: 15 },
  { id: 6, title: "Why Has Nobody Told Me This Before", price: 15 },
  { id: 7, title: "Too Much and Never Enough", price: 16 },
  { id: 8, title: "The 80 Out of 20 Principle", price: 15 },
  { id: 9, title: "Seduction", price: 16 },
  { id: 10, title: "Outliers", price: 13 },
  { id: 11, title: "Declutter Your Mind", price: 15 },
  { id: 12, title: "Blue Ocean Strategy", price: 20 },
  { id: 13, title: "Getting Over You", price: 13 },
  { id: 14, title: "The Everyday Hero", price: 15 },
  { id: 15, title: "Before the Coffee Gets Cold", price: 13 },
  { id: 16, title: "Harvard Business Review Manager Handbook", price: 20 },
  { id: 17, title: "Think and Grow Rich", price: 15 },
  { id: 18, title: "The 5 Love Languages", price: 15 },
  { id: 19, title: "The Four Agreements", price: 14 },
  { id: 20, title: "The Power of Habits", price: 15 },
  { id: 21, title: "Before We Say Goodbye", price: 13 },
  { id: 22, title: "Elon Musk Tesla, SpaceX and the Quest for a Fantastic Future", price: 20 },
  { id: 23, title: "A Brilliant Madness", price: 13 },
  { id: 24, title: "The Art of War", price: 13 },
  { id: 25, title: "Think Like a Monk", price: 15 },
  { id: 26, title: "The Mountain Is You", price: 14 },
  { id: 27, title: "The Daily Stoic", price: 16 },
  { id: 28, title: "Thinking Fast and Slow", price: 16 },
  { id: 29, title: "The 7 Habits of Highly Effective People", price: 15 },
  { id: 30, title: "Surrounded by Psychopaths", price: 15 },
  { id: 31, title: "It Ends With Us", price: 14 },
  { id: 32, title: "Side Hustle", price: 15 },
  { id: 33, title: "The First 90 Days", price: 16 },
  { id: 34, title: "How to Win Friends and Influence People", price: 14 },
  { id: 35, title: "Effortless", price: 14 },
  { id: 36, title: "The Rules of Wealth", price: 15 },
  { id: 37, title: "The Light We Carry", price: 16 },
  { id: 38, title: "Finding Me", price: 16 },
  { id: 39, title: "The 48 Laws of Power", price: 16 },
  { id: 40, title: "Anxious for Nothing", price: 15 },
  { id: 41, title: "Present Over Perfect", price: 15 },
  { id: 42, title: "You Can Heal Your Life", price: 14 },
  { id: 43, title: "Man's Search for Meaning", price: 14 },
  { id: 44, title: "Can't Hurt Me", price: 16 },
  { id: 45, title: "The 10X Rule", price: 16 },
  { id: 46, title: "The 5AM Club", price: 15 },
  { id: 47, title: "Surrounded by Idiots", price: 15 },
  { id: 48, title: "Broken Flowers", price: 14 },
  { id: 49, title: "I Will Teach You to Be Rich", price: 14 },
  { id: 50, title: "Mindset", price: 15 },
  { id: 51, title: "Atomic Habits", price: 15 },
  { id: 52, title: "Find Your Why", price: 14 },
  { id: 53, title: "Eat That Frog", price: 13 },
  { id: 54, title: "The Subtle Art of Not Giving a Fuck", price: 16 },
  { id: 55, title: "101 Essays That Will Change the Way You Think", price: 16 },
  { id: 56, title: "Influence The Psychology of Persuasion", price: 15 },
  { id: 57, title: "Ikigai The Japanese Secret to a Long and Happy Life", price: 16 },
  { id: 58, title: "The Inevitable", price: 15 },
  { id: 59, title: "13 Things Mentally Strong People Don't Do", price: 18 },
  { id: 60, title: "Extreme Ownership", price: 18 },
  { id: 61, title: "Humans A Brief History of How We Fucked Up", price: 18 },
  { id: 62, title: "Zero to One", price: 15 },
  { id: 63, title: "It Starts With Us", price: 13 },
  { id: 64, title: "Who Moved My Cheese", price: 10 },
  { id: 65, title: "Deep Work", price: 18 },
  { id: 66, title: "The Alchemist", price: 15 },
  { id: 67, title: "Rich Dad Poor Dad", price: 12 },
  { id: 68, title: "Never Finished", price: 17 },
  { id: 69, title: "The $100 Startup", price: 15 }
];

export default books;
