const books = [
  { id: 1, title: "The Effective Executive", price: 15, image: "/books/effective-executive.jpg" },
  { id: 2, title: "The Good Girl's Guide to Being a Dick", price: 12, image: "/books/good-girls-guide.jpg" },
  { id: 3, title: "Ted Talks", price: 13, image: "/books/ted-talks.jpg" },
  { id: 4, title: "All in on AI", price: 15, image: "/books/all-in-on-ai.jpg" },
  { id: 5, title: "The Power of Your Subconscious Mind", price: 15, image: "/books/subconscious-mind.jpg" },
  { id: 6, title: "Why Has Nobody Told Me This Before", price: 15, image: "/books/why-nobody-told-me.jpg" },
  { id: 7, title: "Too Much and Never Enough", price: 16, image: "/books/too-much.jpg" },
  { id: 8, title: "The 80 out of 20 Principle", price: 15, image: "/books/80-out-of-20.jpg" },
  { id: 9, title: "Seduction", price: 16, image: "/books/seduction.jpg" },
  { id: 10, title: "Outliers", price: 13, image: "/books/outliers.jpg" },
  { id: 11, title: "Declutter Your Mind", price: 15, image: "/books/declutter.jpg" },
  { id: 12, title: "Blue Ocean Strategy", price: 20, image: "/books/blue-ocean.jpg" },
  { id: 13, title: "Getting Over You", price: 13, image: "/books/getting-over-you.jpg" },
  { id: 14, title: "The Everyday Hero", price: 15, image: "/books/everyday-hero.jpg" },
  { id: 15, title: "Before the Coffee Gets Cold", price: 13, image: "/books/coffee-gets-cold.jpg" },
  { id: 16, title: "Harvard Business Review Manager Handbook", price: 20, image: "/books/hbr-handbook.jpg" },
  { id: 17, title: "Think and Grow Rich", price: 15, image: "/books/think-grow-rich.jpg" },
  { id: 18, title: "The Five Love Languages", price: 15, image: "/books/five-love-languages.jpg" },
  { id: 19, title: "The Four Agreements", price: 14, image: "/books/four-agreements.jpg" },
  { id: 20, title: "The Power of Habits", price: 15, image: "/books/power-of-habits.jpg" },
  { id: 21, title: "Before We Say Goodbye", price: 13, image: "/books/say-goodbye.jpg" },
  { id: 22, title: "Elon Musk Tesla SpaceX and the Quest for a Fantastic Future", price: 20, image: "/books/elon-musk.jpg" },
  { id: 23, title: "A Brilliant Madness", price: 13, image: "/books/brilliant-madness.jpg" },
  { id: 24, title: "The Art of War", price: 13, image: "/books/art-of-war.jpg" },
  { id: 25, title: "Think Like a Monk", price: 15, image: "/books/think-like-a-monk.jpg" },
  { id: 26, title: "The Mountain Is You", price: 14, image: "/books/mountain-is-you.jpg" },
  { id: 27, title: "The Daily Stoic", price: 16, image: "/books/daily-stoic.jpg" },
  { id: 28, title: "Thinking Fast and Slow", price: 16, image: "/books/thinking-fast-slow.jpg" },
  { id: 29, title: "The Seven Habits of Highly Effective People", price: 15, image: "/books/seven-habits.jpg" },
  { id: 30, title: "Surrounded by Psychopaths", price: 15, image: "/books/psychopaths.jpg" },
  { id: 31, title: "It Ends With Us", price: 14, image: "/books/it-ends-with-us.jpg" },
  { id: 32, title: "Side Hustle", price: 15, image: "/books/side-hustle.jpg" },
  { id: 33, title: "The First Ninety Days", price: 16, image: "/books/first-ninety-days.jpg" },
  { id: 34, title: "How to Win Friends and Influence People", price: 14, image: "/books/win-friends.jpg" },
  { id: 35, title: "Effortless", price: 14, image: "/books/effortless.jpg" },
  { id: 36, title: "The Rules of Wealth", price: 15, image: "/books/rules-of-wealth.jpg" },
  { id: 37, title: "The Light We Carry", price: 16, image: "/books/light-we-carry.jpg" },
  { id: 38, title: "Finding Me", price: 16, image: "/books/finding-me.jpg" },
  { id: 39, title: "The Forty Eight Laws of Power", price: 16, image: "/books/48-laws.jpg" },
  { id: 40, title: "Anxious for Nothing", price: 15, image: "/books/anxious.jpg" },
  { id: 41, title: "Present Over Perfect", price: 15, image: "/books/present-over-perfect.jpg" },
  { id: 42, title: "You Can Heal Your Life", price: 14, image: "/books/heal-your-life.jpg" },
  { id: 43, title: "Man Search for Meaning", price: 14, image: "/books/search-for-meaning.jpg" },
  { id: 44, title: "Cant Hurt Me", price: 16, image: "/books/cant-hurt-me.jpg" },
  { id: 45, title: "The Ten X Rule", price: 16, image: "/books/10x-rule.jpg" },
  { id: 46, title: "The Five AM Club", price: 15, image: "/books/5am-club.jpg" },
  { id: 47, title: "Surrounded by Idiots", price: 15, image: "/books/idiots.jpg" },
  { id: 48, title: "Broken Flowers", price: 14, image: "/books/broken-flowers.jpg" },
  { id: 49, title: "I Will Teach You to Be Rich", price: 14, image: "/books/teach-you-rich.jpg" },
  { id: 50, title: "Mindset", price: 15, image: "/books/mindset.jpg" },
  { id: 51, title: "Atomic Habits", price: 15, image: "/books/atomic-habits.jpg" },
  { id: 52, title: "Find Your Why", price: 14, image: "/books/find-your-why.jpg" },
  { id: 53, title: "Eat That Frog", price: 13, image: "/books/eat-that-frog.jpg" },
  { id: 54, title: "The Subtle Art of Not Giving a Fuck", price: 16, image: "/books/subtle-art.jpg" },
  { id: 55, title: "One Hundred One Essays That Will Change the Way You Think", price: 16, image: "/books/101-essays.jpg" },
  { id: 56, title: "Influence The Psychology of Persuasion", price: 15, image: "/books/influence.jpg" },
  { id: 57, title: "Ikigai The Japanese Secret to a Long and Happy Life", price: 16, image: "/books/ikigai.jpg" },
  { id: 58, title: "The Inevitable", price: 15, image: "/books/inevitable.jpg" },
  { id: 59, title: "Thirteen Things Mentally Strong People Dont Do", price: 18, image: "/books/mentally-strong.jpg" },
  { id: 60, title: "Extreme Ownership", price: 18, image: "/books/extreme-ownership.jpg" },
  { id: 61, title: "Humans A Brief History of How We Fucked Up", price: 18, image: "/books/humans.jpg" },
  { id: 62, title: "Zero to One", price: 15, image: "/books/zero-to-one.jpg" },
  { id: 63, title: "It Starts With Us", price: 13, image: "/books/it-starts-with-us.jpg" },
  { id: 64, title: "Who Moved My Cheese", price: 10, image: "/books/moved-my-cheese.jpg" },
  { id: 65, title: "Deep Work", price: 18, image: "/books/deep-work.jpg" },
  { id: 66, title: "The Alchemist", price: 15, image: "/books/alchemist.jpg" },
  { id: 67, title: "Rich Dad Poor Dad", price: 12, image: "/books/rich-dad-poor-dad.jpg" },
  { id: 68, title: "Never Finished", price: 17, image: "/books/never-finished.jpg" },
  { id: 69, title: "The One Hundred Dollar Startup", price: 15, image: "/books/100-dollar-startup.jpg" }
];

export default books;
